# This is a basic workflow to help you get started with Actions

name: Deploy Kot

# Controls when the workflow will run
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Run it
      run: dotnet run --project Kocislav.Discord/ --property:Configuration=Release

